CREATE TABLE CALENDAR(
	CALNO NUMBER(38) NOT NULL,
	CALYEAR VARCHAR2(10) NOT NULL,
	CALMONTH VARCHAR2(10) NOT NULL,
	CALDAY VARCHAR2(10) NOT NULL,
	CALTIME VARCHAR2(10) NOT NULL,
	CALREQ VARCHAR2(10) NOT NULL,
	CALDATE DATE NOT NULL,
	CALCONTENTS VARCHAR2(50),
	USE_YN VARCHAR(2) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE CALENDAR_SEQ;
